space_group_number_sup = 2
space_group_number_sub = 1
basis_change = [[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, 1.0]]
origin_shift = [0.0, 0.0, 0.0]

[wycksplit]
[wycksplit.2i]
[wycksplit.2i.1a1]
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]
[wycksplit.2i.1a2]
basis_change = [[-1, 0, 0], [0, -1, 0], [0, 0, -1]]
origin_shift = [0.0, 0.0, 0.0]
[wycksplit.1h]
[wycksplit.1h.1a1]
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]
[wycksplit.1g]
[wycksplit.1g.1a1]
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]
[wycksplit.1f]
[wycksplit.1f.1a1]
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]
[wycksplit.1e]
[wycksplit.1e.1a1]
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]
[wycksplit.1d]
[wycksplit.1d.1a1]
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]
[wycksplit.1c]
[wycksplit.1c.1a1]
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]
[wycksplit.1b]
[wycksplit.1b.1a1]
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]
[wycksplit.1a]
[wycksplit.1a.1a1]
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]
