space_group_number_sup = 5
space_group_number_sub = 1
basis_change = [[0.5, 0.5, 0.0], [-0.5, 0.5, 0.0], [0.0, 0.0, 1.0]]
origin_shift = [0.0, 0.0, 0.0]

[[coset_representatives]]
rotation = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
translation = [0.0, 0.0, 0.0]
[[coset_representatives]]
rotation = [[-1, 0, 0], [0, 1, 0], [0, 0, -1]]
translation = [0.0, 0.0, 0.0]

[wycksplit]
"4c" = {"1a1" = 0, "1a2" = 1}
"2b" = {"1a1" = 0}
"2a" = {"1a1" = 0}
