space_group_number_sup = 8
space_group_number_sub = 1
basis_change = [[0.5, 0.5, 0.0], [-0.5, 0.5, 0.0], [0.0, 0.0, 1.0]]
origin_shift = [0.0, 0.0, 0.0]

[[coset_representatives]]
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]
[[coset_representatives]]
basis_change = [[1, 0, 0], [0, -1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]

[wycksplit]
"4a" = {"1a1" = 0, "1a2" = 1}
"2a" = {"1a1" = 0}
