space_group_number_sup = 10
space_group_number_sub = 2
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]

[[coset_representatives]]
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]
[[coset_representatives]]
basis_change = [[-1, 0, 0], [0, 1, 0], [0, 0, -1]]
origin_shift = [0.0, 0.0, 0.0]

[wycksplit]
"4o" = {"2i1" = 0, "2i2" = 1}
"2n" = {"2i1" = 0}
"2m" = {"2i1" = 0}
"2l" = {"2i1" = 0}
"2k" = {"2i1" = 0}
"2j" = {"2i1" = 0}
"2i" = {"2i1" = 0}
"1h" = {"1h1" = 0}
"1g" = {"1f1" = 0}
"1f" = {"1g1" = 0}
"1e" = {"1e1" = 0}
"1d" = {"1d1" = 0}
"1c" = {"1b1" = 0}
"1b" = {"1c1" = 0}
"1a" = {"1a1" = 0}
