space_group_number_sup = 11
space_group_number_sub = 6
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.25, 0.0]

[[coset_representatives]]
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]
[[coset_representatives]]
basis_change = [[-1, 0, 0], [0, -1, 0], [0, 0, -1]]
origin_shift = [0.0, 0.0, 0.0]

[wycksplit]
"4f" = {"2c1" = 0, "2c2" = 1}
"2e" = {"1a1" = 0, "1b1" = 1}
"2d" = {"2c1" = 0}
"2c" = {"2c1" = 0}
"2b" = {"2c1" = 0}
"2a" = {"2c1" = 0}
