space_group_number_sup = 12
space_group_number_sub = 8
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]

[[coset_representatives]]
rotation = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
translation = [0.0, 0.0, 0.0]
[[coset_representatives]]
rotation = [[-1, 0, 0], [0, -1, 0], [0, 0, -1]]
translation = [0.0, 0.0, 0.0]

[wycksplit]
"8j" = {"4b1" = 0, "4b2" = 1}
"4i" = {"2a1" = 0, "2a2" = 1}
"4h" = {"4b1" = 0}
"4g" = {"4b1" = 0}
"4f" = {"4b1" = 0}
"4e" = {"4b1" = 0}
"2d" = {"2a1" = 0}
"2c" = {"2a1" = 0}
"2b" = {"2a1" = 0}
"2a" = {"2a1" = 0}
