space_group_number_sup = 12
space_group_number_sub = 2
basis_change = [[0.5, 0.5, 0.0], [-0.5, 0.5, 0.0], [0.0, 0.0, 1.0]]
origin_shift = [0.0, 0.0, 0.0]

[[coset_representatives]]
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]
[[coset_representatives]]
basis_change = [[-1, 0, 0], [0, 1, 0], [0, 0, -1]]
origin_shift = [0.0, 0.0, 0.0]

[wycksplit]
"8j" = {"2i1" = 0, "2i2" = 1}
"4i" = {"2i1" = 0}
"4h" = {"2i1" = 0}
"4g" = {"2i1" = 0}
"4f" = {"1g1" = 0, "1f1" = 1}
"4e" = {"1c1" = 0, "1d1" = 1}
"2d" = {"1h1" = 0}
"2c" = {"1b1" = 0}
"2b" = {"1e1" = 0}
"2a" = {"1a1" = 0}
