space_group_number_sup = 12
space_group_number_sub = 5
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]

[[coset_representatives]]
rotation = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
translation = [0.0, 0.0, 0.0]
[[coset_representatives]]
rotation = [[-1, 0, 0], [0, -1, 0], [0, 0, -1]]
translation = [0.0, 0.0, 0.0]

[wycksplit]
"8j" = {"4c1" = 0, "4c2" = 1}
"4i" = {"4c1" = 0}
"4h" = {"2b1" = 0, "2b2" = 1}
"4g" = {"2a1" = 0, "2a2" = 1}
"4f" = {"4c1" = 0}
"4e" = {"4c1" = 0}
"2d" = {"2b1" = 0}
"2c" = {"2b1" = 0}
"2b" = {"2a1" = 0}
"2a" = {"2a1" = 0}
