space_group_number_sup = 13
space_group_number_sub = 3
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.25]

[[coset_representatives]]
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]
[[coset_representatives]]
basis_change = [[-1, 0, 0], [0, -1, 0], [0, 0, -1]]
origin_shift = [0.0, 0.0, 0.0]

[wycksplit]
"4g" = {"2e1" = 0, "2e2" = 1}
"2f" = {"1c1" = 0, "1d1" = 1}
"2e" = {"1a1" = 0, "1b1" = 1}
"2d" = {"1e1" = 0}
"2c" = {"2e1" = 0}
"2b" = {"2e1" = 0}
"2a" = {"2e1" = 0}
