space_group_number_sup = 14
space_group_number_sub = 7
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.25, 0.0]

[[coset_representatives]]
rotation = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
translation = [0.0, 0.0, 0.0]
[[coset_representatives]]
rotation = [[-1, 0, 0], [0, -1, 0], [0, 0, -1]]
translation = [0.0, 0.0, 0.0]

[wycksplit]
"4e" = {"2a1" = 0, "2a2" = 1}
"2d" = {"2a1" = 0}
"2c" = {"2a1" = 0}
"2b" = {"2a1" = 0}
"2a" = {"2a1" = 0}
