space_group_number_sup = 15
space_group_number_sub = 2
basis_change = [[0.5, 0.5, 0.0], [-0.5, 0.5, 0.0], [0.0, 0.0, 1.0]]
origin_shift = [0.0, 0.0, 0.25]

[[coset_representatives]]
rotation = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
translation = [0.0, 0.0, 0.0]
[[coset_representatives]]  # glide
rotation = [[-1, 0, 0], [0, 1, 0], [0, 0, -1]]
translation = [0.0, 0.0, 0.5]

[wycksplit]
"8f" = {"2i1" = 0, "2i2" = 1}
"4e" = {"2i1" = 0}
"4d" = {"1g1" = 0, "1d1" = 1}
"4c" = {"1c1" = 0, "1f1" = 1}
"4b" = {"1e1" = 0, "1h1" = 1}
"4a" = {"1a1" = 0, "1b1" = 1}
