space_group_number_sup = 15
space_group_number_sub = 5
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.25]

[[coset_representatives]]
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]
[[coset_representatives]]
basis_change = [[-1, 0, 0], [0, -1, 0], [0, 0, -1]]
origin_shift = [0.0, 0.0, 0.0]

[wycksplit]
"8f" = {"4c1" = 0, "4c2" = 1}
"4e" = {"2a1" = 0, "2b2" = 1}
"4d" = {"4c1" = 0}
"4c" = {"4c1" = 0}
"4b" = {"4c1" = 0}
"4a" = {"4c1" = 0}
