space_group_number_sup = 63
space_group_number_sub = 12
basis_change = [[0, 1, 0], [-1, 0, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]

[[coset_representatives]]
rotation = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
translation = [0.0, 0.0, 0.0]
[[coset_representatives]]  # screw
rotation = [[-1, 0, 0], [0, -1, 0], [0, 0, 1]]
translation = [0.0, 0.0, 0.5]

[wycksplit]
"16h" = {"8j1" = 0, "8j2" = 1}
"8g" = {"8j1" = 0}
"8f" = {"4i1" = 0, "4i2" = 1}
"8e" = {"4g1" = 0, "4h1" = 1}
"8d" = {"4e1" = 0, "4f1" = 1}
"4c" = {"4i1" = 0}
"4b" = {"2b1" = 0, "2d1" = 1}
"4a" = {"2a1" = 0, "2c1" = 1}
