space_group_number_sup = 63
space_group_number_sub = 11
basis_change = [[0.5, 0.0, 0.5], [0.5, 0.0, -0.5], [0.0, 1.0, 0.0]]
origin_shift = [0.0, 0.0, 0.0]

[[coset_representatives]]
rotation = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
translation = [0.0, 0.0, 0.0]
[[coset_representatives]]
rotation = [[1, 0, 0], [0, -1, 0], [0, 0, -1]]
translation = [0.0, 0.0, 0.0]

[wycksplit]
"16h" = {"4f1" = 0, "4f2" = 1}
"8g" = {"2e1" = 0, "2e2" = 1}
"8f" = {"4f1" = 0}
"8e" = {"4f1" = 0}
"8d" = {"2b1" = 0, "2c1" = 1}
"4c" = {"2e1" = 0}
"4b" = {"2d1" = 0}
"4a" = {"2a1" = 0}
