space_group_number_sup = 63
space_group_number_sub = 40
basis_change = [[0, 0, -1], [0, 1, 0], [1, 0, 0]]
origin_shift = [0.0, 0.0, 0.0]

[[coset_representatives]]
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]
[[coset_representatives]]
basis_change = [[-1, 0, 0], [0, -1, 0], [0, 0, -1]]
origin_shift = [0.0, 0.0, 0.0]

[wycksplit]
"16h" = {"8c1" = 0, "8c2" = 1}
"8g" = {"4b1" = 0, "4c1" = 1}
"8f" = {"8c1" = 0}
"8e" = {"4a1" = 0, "4a2" = 1}
"8d" = {"8c1" = 0}
"4c" = {"4b1" = 0}
"4b" = {"4a1" = 0}
"4a" = {"4a1" = 0}
