space_group_number_sup = 70
space_group_number_sub = 43
basis_change = [[0, 0, 1], [1, 0, 0], [0, 1, 0]]
origin_shift = [0.0, 0.375, 0.375]

[[coset_representatives]]
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]
[[coset_representatives]]
basis_change = [[-1, 0, 0], [0, -1, 0], [0, 0, -1]]
origin_shift = [0.0, 0.0, 0.0]

[wycksplit]
"32h" = {"16b1" = 0, "16b2" = 1}
"16g" = {"16b1" = 0}
"16f" = {"16b1" = 0}
"16e" = {"8a1" = 0, "8a2" = 1}
"16d" = {"16b1" = 0}
"16c" = {"16b1" = 0}
"8b" = {"8a1" = 0}
"8a" = {"8a1" = 0}
