space_group_number_sup = 70
space_group_number_sub = 22
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.125, 0.125, 0.125]

[[coset_representatives]]
rotation = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
translation = [0.0, 0.0, 0.0]
[[coset_representatives]]
rotation = [[-1, 0, 0], [0, -1, 0], [0, 0, -1]]
translation = [0.0, 0.0, 0.0]

[wycksplit]
"32h" = {"16k1" = 0, "16k2" = 1}
"16g" = {"8g1" = 0, "8h1" = 1}
"16f" = {"8f1" = 0, "8i1" = 1}
"16e" = {"8e1" = 0, "8j2" = 1}
"16d" = {"16k1" = 0}
"16c" = {"16k1" = 0}
"8b" = {"4b1" = 0, "4c1" = 1}
"8a" = {"4a1" = 0, "4d1" = 1}
