space_group_number_sup = 88
space_group_number_sub = 15
basis_change = [[-1, 0, 0], [-1, 0, 1], [0, 1, 0]]
origin_shift = [0.0, 0.0, 0.0]

[[coset_representatives]]
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]
[[coset_representatives]]  # screw
basis_change = [[0, -1, 0], [1, 0, 0], [0, 0, 1]]
origin_shift = [-0.25, 0.25, 0.25]

[wycksplit]
"16f" = {"8f1" = 0, "8f2" = 1}
"8e" = {"4e1" = 0, "4e2" = 1}
"8d" = {"4b1" = 0, "4c1" = 1}
"8c" = {"4a1" = 0, "4d1" = 1}
"4b" = {"4e1" = 0}
"4a" = {"4e1" = 0}
