space_group_number_sup = 88
space_group_number_sub = 82
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.25, 0.625]

[[coset_representatives]]
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]
[[coset_representatives]]
basis_change = [[-1, 0, 0], [0, -1, 0], [0, 0, -1]]
origin_shift = [0.0, 0.0, 0.0]

[wycksplit]
"16f" = {"8g1" = 0, "8g2" = 1}
"8e" = {"4e1" = 0, "4f1" = 1}
"8d" = {"8g1" = 0}
"8c" = {"8g1" = 0}
"4b" = {"2a1" = 0, "2d1" = 1}
"4a" = {"2b1" = 0, "2c1" = 1}
