space_group_number_sup = 141
space_group_number_sub = 119
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.25, 0.375]

[[coset_representatives]]
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]
[[coset_representatives]]
basis_change = [[-1, 0, 0], [0, -1, 0], [0, 0, -1]]
origin_shift = [0.0, 0.0, 0.0]

[wycksplit]
"32i" = {"16j1" = 0, "16j2" = 1}
"16h" = {"8i1" = 0, "8i2" = 1}
"16g" = {"8g1" = 0, "8h1" = 1}
"16f" = {"16j1" = 0}
"8e" = {"4e1" = 0, "4f2" = 1}
"8d" = {"8i1" = 0}
"8c" = {"8i1" = 0}
"4b" = {"2a1" = 0, "2c1" = 1}
"4a" = {"2d1" = 0, "2b1" = 1}
