space_group_number_sup = 141
space_group_number_sub = 98
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.25, 0.375]

[[coset_representatives]]
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]
[[coset_representatives]]
basis_change = [[-1, 0, 0], [0, -1, 0], [0, 0, -1]]
origin_shift = [0.0, 0.0, 0.0]

[wycksplit]
"32i" = {"16g1" = 0, "16g2" = 1}
"16h" = {"16g1" = 0}
"16g" = {"8d1" = 0, "8e1" = 1}
"16f" = {"8f1" = 0, "8f2" = 1}
"8e" = {"8c1" = 0}
"8d" = {"8f1" = 0}
"8c" = {"8f1" = 0}
"4b" = {"4a1" = 0}
"4a" = {"4b1" = 0}
