space_group_number_sup = 141
space_group_number_sub = 109
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.25, 0.0]

[[coset_representatives]]
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]
[[coset_representatives]]
basis_change = [[-1, 0, 0], [0, -1, 0], [0, 0, -1]]
origin_shift = [0.0, 0.0, 0.0]

[wycksplit]
"32i" = {"16c1" = 0, "16c2" = 1}
"16h" = {"8b1" = 0, "8b2" = 1}
"16g" = {"16c1" = 0}
"16f" = {"16c1" = 0}
"8e" = {"4c1" = 0, "4a2" = 1}
"8d" = {"8b1" = 0}
"8c" = {"8b1" = 0}
"4b" = {"4a1" = 0}
"4a" = {"4a1" = 0}
