space_group_number_sup = 141
space_group_number_sub = 88
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.5, 0.0]

[[coset_representatives]]
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]
[[coset_representatives]]  # reflection
basis_change = [[-1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]

[wycksplit]
"32i" = {"16f1" = 0, "16f2" = 1}
"16h" = {"16f1" = 0}
"16g" = {"16f1" = 0}
"16f" = {"16f1" = 0}
"8e" = {"8e1" = 0}
"8d" = {"8d1" = 0}
"8c" = {"8c1" = 0}
"4b" = {"4b1" = 0}
"4a" = {"4a1" = 0}
