space_group_number_sup = 141
space_group_number_sub = 70
basis_change = [[1, 1, 0], [-1, 1, 0], [0, 0, 1]]
origin_shift = [0.25, 0.75, 0.25]

[[coset_representatives]]
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]
[[coset_representatives]]  # reflection
basis_change = [[-1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]

[wycksplit]
"32i" = {"32h1" = 0, "32h2" = 1}
"16h" = {"32h1" = 0}
"16g" = {"16f1" = 0, "16f2" = 1}
"16f" = {"32h1" = 0}
"8e" = {"16g1"= 0}
"8d" = {"16d1"= 0}
"8c" = {"16c1"= 0}
"4b" = {"8b1" = 0}
"4a" = {"8a1" = 0}
