space_group_number_sup = 164
space_group_number_sub = 150
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]

[[coset_representatives]]
rotation = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
translation = [0.0, 0.0, 0.0]
[[coset_representatives]]
rotation = [[-1, 0, 0], [0, -1, 0], [0, 0, -1]]
translation = [0.0, 0.0, 0.0]

[wycksplit]
"12j" = {"6g1" = 0, "6g2" = 1}
"6i" = {"6g1" = 0}
"6h" = {"3f1" = 0, "3f2" = 1}
"6g" = {"3e1" = 0, "3e2" = 1}
"3f" = {"3f1" = 0}
"3e" = {"3e1" = 0}
"2d" = {"2d1" = 0}
"2c" = {"2c1" = 0}
"1b" = {"1b1" = 0}
"1a" = {"1a1" = 0}
