space_group_number_sup = 166
space_group_number_sub = 160
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]

[[coset_representatives]]
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]
[[coset_representatives]]
basis_change = [[-1, 0, 0], [0, -1, 0], [0, 0, -1]]
origin_shift = [0.0, 0.0, 0.0]

[wycksplit]
"36i" = {"18c1" = 0, "18c2" = 1}
"18h" = {"9b1" = 0, "9b2" = 1}
"18g" = {"18c1" = 0}
"18f" = {"18c1" = 0}
"9e" = {"9b1" = 0}
"9d" = {"9b1" = 0}
"6c" = {"3a1" = 0, "3a2" = 1}
"3b" = {"3a1" = 0}
"3a" = {"3a1" = 0}
