space_group_number_sup = 166
space_group_number_sub = 155
basis_change = [[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, 1.0]]
origin_shift = [0.0, 0.0, 0.0]

[[coset_representatives]]
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]
[[coset_representatives]]
basis_change = [[-1, 0, 0], [0, -1, 0], [0, 0, -1]]
origin_shift = [0.0, 0.0, 0.0]

[wycksplit]
"36i" = {"18f1" = 0, "18f2" = 1}
"18h" = {"18f1" = 0}
"18g" = {"9e1" = 0, "9e2" = 1}
"18f" = {"9d1" = 0, "9d2" = 1}
"9e" = {"9d1" = 0}
"9d" = {"9e1" = 0}
"6c" = {"6c1" = 0}
"3b" = {"3b1" = 0}
"3a" = {"3a1" = 0}
