space_group_number_sup = 166
space_group_number_sub = 12
basis_change = [[-0.3333333333333333, -1.0, 0.0], [0.3333333333333333, -1.0, 0.0], [-0.6666666666666666, 0.0, 1.0]]
origin_shift = [0.0, 0.0, 0.0]

[wycksplit]
[wycksplit.36i]
[wycksplit.36i.8j1]
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]
[wycksplit.36i.8j2]
basis_change = [[0, 1, 0], [-1, 1, 0], [0, 0, -1]]
origin_shift = [0.0, 0.0, 0.0]
[wycksplit.36i.8j3]
basis_change = [[-1, 0, 0], [-1, 1, 0], [0, 0, -1]]
origin_shift = [0.0, 0.0, 0.0]
[wycksplit.18h]
[wycksplit.18h.4i1]
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]
[wycksplit.18h.8j1]
basis_change = [[-1, 0, 0], [-1, 1, 0], [0, 0, -1]]
origin_shift = [0.0, 0.0, 0.0]
[wycksplit.18g]
[wycksplit.18g.8j1]
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]
[wycksplit.18g.4h1]
basis_change = [[-1, 0, 0], [-1, 1, 0], [0, 0, -1]]
origin_shift = [0.0, 0.0, 0.0]
[wycksplit.18f]
[wycksplit.18f.8j1]
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]
[wycksplit.18f.4g1]
basis_change = [[-1, 0, 0], [-1, 1, 0], [0, 0, -1]]
origin_shift = [0.0, 0.0, 0.0]
[wycksplit.9e]
[wycksplit.9e.4f1]
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]
[wycksplit.9e.2b1]
basis_change = [[-1, 0, 0], [-1, 1, 0], [0, 0, -1]]
origin_shift = [0.0, 0.0, 0.0]
[wycksplit.9d]
[wycksplit.9d.4e1]
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]
[wycksplit.9d.2d1]
basis_change = [[0, 1, 0], [-1, 1, 0], [0, 0, -1]]
origin_shift = [0.0, 0.0, 0.0]
[wycksplit.6c]
[wycksplit.6c.4i1]
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]
[wycksplit.3b]
[wycksplit.3b.2c1]
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]
[wycksplit.3a]
[wycksplit.3a.2a1]
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]
