space_group_number_sup = 176
space_group_number_sub = 11
basis_change = [[0, 0, 1], [1, 0, 0], [0, 1, 0]]
origin_shift = [0.0, 0.0, 0.0]

[[coset_representatives]]  # (x, y, z)
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]
[[coset_representatives]]  # (-y, x-y, z)
basis_change = [[0, -1, 0], [1, -1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]
[[coset_representatives]]  # (-x+y, -x, z)
basis_change = [[-1, 1, 0], [-1, 0, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]

[wycksplit]
"12i" = {"4f1" = 0, "4f2" = 1, "4f3" = 2}
"6h" = {"2e1" = 0, "2e2" = 1, "2e3" = 2}
"6g" = {"2c1" = 0, "2c2" = 1, "2c3" = 2}
"4f" = {"4f1" = 0}
"4e" = {"4f1" = 0}
"2d" = {"2e1" = 0}
"2c" = {"2e1" = 0}
"2b" = {"2a1" = 0}
"2a" = {"2e1" = 0}
