space_group_number_sup = 182
space_group_number_sub = 150
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]

[[coset_representatives]]
rotation = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
translation = [0.0, 0.0, 0.0]
[[coset_representatives]]  # screw
rotation = [[-1, 0, 0], [0, -1, 0], [0, 0, 1]]
translation = [0.0, 0.0, 0.5]

[wycksplit]
"12i" = {"6g1" = 0, "6g2" = 1}
"6h" = {"6g1" = 0}
"6g" = {"3e1" = 0, "3f1" = 1}
"4f" = {"2d1" = 0, "2d2" = 1}
"4e" = {"2c1" = 0, "2c2" = 1}
"2d" = {"2d1" = 0}
"2c" = {"2d1" = 0}
"2b" = {"2c1" = 0}
"2a" = {"1a1" = 0, "1b1" = 1}
