space_group_number_sup = 186
space_group_number_sub = 156
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]

[[coset_representatives]]
rotation = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
translation = [0.0, 0.0, 0.0]
[[coset_representatives]]  # screw
rotation = [[-1, 0, 0], [0, -1, 0], [0, 0, 1]]
translation = [0.0, 0.0, 0.5]

[wycksplit]
"12d" = {"6e1" = 0, "6e2" = 1}
"6c" = {"3d1" = 0, "3d2" = 1}
"2b" = {"1b1" = 0, "1b2" = 1}
"2a" = {"1a1" = 0, "1a2" = 1}
