space_group_number_sup = 187
space_group_number_sub = 156
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]

[[coset_representatives]]
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]
[[coset_representatives]]
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, -1]]
origin_shift = [0.0, 0.0, 0.0]

[wycksplit]
"12o" = {"6e1" = 0, "6e2" = 1}
"6n" = {"3d1" = 0, "3d2" = 1}
"6m" = {"6e1" = 0}
"6l" = {"6e2" = 0}
"3k" = {"3d1" = 0}
"3j" = {"3d1" = 0}
"2i" = {"1c1" = 0, "1c2" = 1}
"2h" = {"1b1" = 0, "1b2" = 1}
"2g" = {"1a1" = 0, "1a2" = 1}
"1f" = {"1c1" = 0}
"1e" = {"1c1" = 0}
"1d" = {"1b1" = 0}
"1c" = {"1b1" = 0}
"1b" = {"1a1" = 0}
"1a" = {"1a1" = 0}
