space_group_number_sup = 187
space_group_number_sub = 38
basis_change = [[0, -1, 1], [0, -1, -1], [1, 0, 0]]
origin_shift = [0.0, 0.0, 0.0]

[[coset_representatives]]  # (x, y, z)
rotation = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
translation = [0.0, 0.0, 0.0]
[[coset_representatives]]  # (-y, x-y, z)
rotation = [[0, -1, 0], [1, -1, 0], [0, 0, 1]]
translation = [0.0, 0.0, 0.0]
[[coset_representatives]]  # (-x+y, -x, z)
rotation = [[-1, 1, 0], [-1, 0, 0], [0, 0, 1]]
translation = [0.0, 0.0, 0.0]

[wycksplit]
"12o" = {"8f1" = 0, "8f2" = 1, "8f3" = 2}
"6n" = {"4c1" = 0, "8f1" = 2}
"6m" = {"4e1" = 0, "4e2" = 1, "4e3" = 2}
"6l" = {"4d1" = 0, "4d2" = 1, "4d3" = 2}
"3k" = {"2b1" = 0, "4e1" = 2}
"3j" = {"2a1" = 0, "4d1" = 2}
"2i" = {"4c1" = 0}
"2h" = {"4c1" = 0}
"2g" = {"4c1" = 0}
"1f" = {"2b1" = 0}
"1e" = {"2a1" = 0}
"1d" = {"2b1" = 0}
"1c" = {"2a1" = 0}
"1b" = {"2b1" = 0}
"1a" = {"2a1" = 0}
