space_group_number_sup = 190
space_group_number_sub = 40
basis_change = [[0, -1, -1], [0, 1, -1], [1, 0, 0]]
origin_shift = [0.0, 0.0, 0.0]

[[coset_representatives]]  # (x, y, z)
rotation = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
translation = [0.0, 0.0, 0.0]
[[coset_representatives]]  # (-y, x-y, z)
rotation = [[0, -1, 0], [1, -1, 0], [0, 0, 1]]
translation = [0.0, 0.0, 0.0]
[[coset_representatives]]  # (-x+y, -x, z)
rotation = [[-1, 1, 0], [-1, 0, 0], [0, 0, 1]]
translation = [0.0, 0.0, 0.0]

[wycksplit]
"12i" = {"8c1" = 0, "8c2" = 1, "8c3" = 2}
"6h" = {"4b1" = 0, "4b2" = 1, "4b3" = 2}
"6g" = {"8c1" = 0, "4a1" = 2}
"4f" = {"8c1" = 0}
"4e" = {"8c1" = 0}
"2d" = {"4b1" = 0}
"2c" = {"4b1" = 0}
"2b" = {"4b1" = 0}
"2a" = {"4a1" = 0}
