space_group_number_sup = 194
space_group_number_sub = 187
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.25]

[[coset_representatives]]
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]
[[coset_representatives]]
basis_change = [[-1, 0, 0], [0, -1, 0], [0, 0, -1]]
origin_shift = [0.0, 0.0, 0.0]

[wycksplit]
"24l" = {"12o1" = 0, "12o2" = 1}
"12k" = {"6n1" = 0, "6n2" = 1}
"12j" = {"6l1" = 0, "6m1" = 1}
"12i" = {"12o1" = 0}
"6h" = {"3j1" = 0, "3k1" = 1}
"6g" = {"6n1" = 0}
"4f" = {"2h1" = 0, "2i1" = 1}
"4e" = {"2g1" = 0, "2g2" = 1}
"2d" = {"1d1" = 0, "1e1" = 1}
"2c" = {"1c1" = 0, "1f1" = 1}
"2b" = {"1a1" = 0, "1b1" = 1}
"2a" = {"2g1" = 0}
