space_group_number_sup = 194
space_group_number_sub = 63
basis_change = [[-1, 1, 0], [-1, -1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]

[[coset_representatives]]  # (x, y, z)
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]
[[coset_representatives]]  # (-y, x-y, z)
basis_change = [[0, -1, 0], [1, -1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]
[[coset_representatives]]  # (-x+y, -x, z)
basis_change = [[-1, 1, 0], [-1, 0, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]

[wycksplit]
"24l" = {"16h1" = 0, "16h2" = 1, "16h3" = 2}
"12k" = {"16h1" = 0, "8f1" = 2}
"12j" = {"8g1" = 0, "8g2" = 1, "8g3" = 2}
"12i" = {"16h1" = 0, "8e1" = 2}
"6h" = {"8g1" = 0, "4c1" = 2}
"6g" = {"8d1" = 0, "4b1" = 2}
"4f" = {"8f1" = 0}
"4e" = {"8f1" = 0}
"2d" = {"4c1" = 0}
"2c" = {"4c1" = 0}
"2b" = {"4c1" = 0}
"2a" = {"4a1" = 0}
