space_group_number_sup = 194
space_group_number_sub = 176
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]

[[coset_representatives]]
rotation = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
translation = [0.0, 0.0, 0.0]
[[coset_representatives]]
rotation = [[0, 1, 0], [1, 0, 0], [0, 0, -1]]
translation = [0.0, 0.0, 0.0]

[wycksplit]
"24l" = {"12i1" = 0, "12i2" = 1}
"12k" = {"12i1" = 0}
"12j" = {"6h1" = 0, "6h2" = 1}
"12i" = {"12i1" = 0}
"6h" = {"6h1" = 0}
"6g" = {"6g1" = 0}
"4f" = {"4f1" = 0}
"4e" = {"4e1" = 0}
"2d" = {"2d1" = 0}
"2c" = {"2c1" = 0}
"2b" = {"2a1" = 0}
"2a" = {"2b1" = 0}
