space_group_number_sup = 203
space_group_number_sub = 148
basis_change = [[-0.5, 0.0, 1.0], [0.5, -0.5, 1.0], [0.0, 0.5, 1.0]]
origin_shift = [0.0, 0.0, 0.0]

[[coset_representatives]]
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]
[[coset_representatives]]
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, -1]]
origin_shift = [0.25, 0.75, 0.5]
[[coset_representatives]]
basis_change = [[1, 0, 0], [0, -1, 0], [0, 0, 1]]
origin_shift = [0.75, 0.5, 0.25]
[[coset_representatives]]
basis_change = [[-1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.5, 0.25, 0.75]

[wycksplit]
"96g" = {"18f1" = 0, "18f2" = 1, "18f3" = 2, "18f4" = 3}
"48f" = {"18f1" = 0, "18f2" = 3}
"32e" = {"6c1" = 0, "18f1" = 3}
"16d" = {"3b1" = 0, "9e1" = 3}
"16c" = {"3a1" = 0, "9d1" = 3}
"8b" = {"6c1" = 0}
"8a" = {"6c1" = 0}
