space_group_number_sup = 210
space_group_number_sub = 98
basis_change = [[0.5, 0.5, 0.0], [-0.5, 0.5, 0.0], [0.0, 0.0, 1.0]]
origin_shift = [0.0, 0.0, 0.0]

[[coset_representatives]]
rotation = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
translation = [0.0, 0.0, 0.0]
[[coset_representatives]]
rotation = [[0, 0, 1], [1, 0, 0], [0, 1, 0]]
translation = [0.0, 0.0, 0.0]
[[coset_representatives]]
rotation = [[0, 1, 0], [0, 0, 1], [1, 0, 0]]
translation = [0.0, 0.0, 0.0]

[wycksplit]
"96h" = {"16g1" = 0, "16g2" = 1, "16g3" = 2}
"48h" = {"16g1" = 0, "8f1" = 1}
"48f" = {"8d1" = 0, "8e1" = 1, "8c1" = 2}
"32e" = {"16g1" = 0}
"16d" = {"8f1" = 0}
"16c" = {"8f1" = 0}
"8b" = {"4b1" = 0}
"8a" = {"4a1" = 0}
