space_group_number_sup = 210
space_group_number_sub = 196
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]

[wycksplit]
[wycksplit.96h]
[wycksplit.96h.48h1]
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]
[wycksplit.96h.48h2]
basis_change = [[0, -1, 0], [-1, 0, 0], [0, 0, -1]]
origin_shift = [0.25, 0.25, 0.25]
[wycksplit.48g]
[wycksplit.48g.48h1]
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]
[wycksplit.48f]
[wycksplit.48f.24f1]
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]
[wycksplit.48f.24g1]
basis_change = [[0, -1, 0], [-1, 0, 0], [0, 0, -1]]
origin_shift = [0.25, 0.25, 0.25]
[wycksplit.32e]
[wycksplit.32e.16e1]
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]
[wycksplit.32e.16e2]
basis_change = [[0, -1, 0], [-1, 0, 0], [0, 0, -1]]
origin_shift = [0.25, 0.25, 0.25]
[wycksplit.16d]
[wycksplit.16d.16e1]
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]
[wycksplit.16c]
[wycksplit.16c.16e1]
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]
[wycksplit.8b]
[wycksplit.8b.4b1]
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]
[wycksplit.8b.4d1]
basis_change = [[0, -1, 0], [-1, 0, 0], [0, 0, -1]]
origin_shift = [0.25, 0.25, 0.25]
[wycksplit.8a]
[wycksplit.8a.4a1]
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]
[wycksplit.8a.4d1]
basis_change = [[0, -1, 0], [-1, 0, 0], [0, 0, -1]]
origin_shift = [0.25, 0.25, 0.25]
