space_group_number_sup = 210
space_group_number_sub = 155
basis_change = [[-0.5, 0.0, 1.0], [0.5, -0.5, 1.0], [0.0, 0.5, 1.0]]
origin_shift = [0.125, 0.125, 0.125]

[wycksplit]
[wycksplit.96h]
[wycksplit.96h.18f1]
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]
[wycksplit.96h.18f2]
basis_change = [[-1, 0, 0], [0, -1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]
[wycksplit.96h.18f3]
basis_change = [[-1, 0, 0], [0, 1, 0], [0, 0, -1]]
origin_shift = [0.0, 0.0, 0.0]
[wycksplit.96h.18f4]
basis_change = [[1, 0, 0], [0, -1, 0], [0, 0, -1]]
origin_shift = [0.0, 0.0, 0.0]
[wycksplit.48g]
[wycksplit.48g.9d1]
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]
[wycksplit.48g.18f1]
basis_change = [[-1, 0, 0], [0, -1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]
[wycksplit.48g.90]
basis_change = [[0, 0, 0], [0, -1, 0], [0, 0, -1]]
origin_shift = [0.0, 0.0, 0.0]
[wycksplit.48f]
[wycksplit.48f.18f1]
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]
[wycksplit.48f.18f2]
basis_change = [[-1, 0, 0], [0, -1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]
[wycksplit.32e]
[wycksplit.32e.6c1]
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]
[wycksplit.32e.18f1]
basis_change = [[-1, 0, 0], [0, -1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]
[wycksplit.16d]
[wycksplit.16d.3b1]
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]
[wycksplit.16d.9d1]
basis_change = [[-1, 0, 0], [0, -1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]
[wycksplit.16c]
[wycksplit.16c.3a1]
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]
[wycksplit.16c.90]
basis_change = [[-1, 0, 0], [0, -1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]
[wycksplit.8b]
[wycksplit.8b.6c1]
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]
[wycksplit.8a]
[wycksplit.8a.6c1]
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]
