space_group_number_sup = 210
space_group_number_sub = 213
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.25, 0.25, 0.25]

[wycksplit]
[wycksplit.96h]
[wycksplit.96h.24e1]
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]
[wycksplit.96h.24e2]
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.5, 0.5]
[wycksplit.96h.24e3]
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.5, 0.0, 0.5]
[wycksplit.96h.24e4]
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.5, 0.5, 0.0]
[wycksplit.16d]
[wycksplit.16d.4a1]
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]
[wycksplit.16d.12d1]
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.5, 0.5, 0.0]
[wycksplit.16c]
[wycksplit.16c.4b1]
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]
[wycksplit.16c.12d1]
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.5, 0.5, 0.0]
[wycksplit.8b]
[wycksplit.8b.8c1]
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]
[wycksplit.8a]
[wycksplit.8a.8c1]
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]
