space_group_number_sup = 216
space_group_number_sub = 119
basis_change = [[0.5, 0.5, 0.0], [-0.5, 0.5, 0.0], [0.0, 0.0, 1.0]]
origin_shift = [0.0, 0.0, 0.0]

[[coset_representatives]]
rotation = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
translation = [0.0, 0.0, 0.0]
[[coset_representatives]]
rotation = [[0, 0, 1], [1, 0, 0], [0, 1, 0]]
translation = [0.0, 0.0, 0.0]
[[coset_representatives]]
rotation = [[0, 1, 0], [0, 0, 1], [1, 0, 0]]
translation = [0.0, 0.0, 0.0]

[wycksplit]
"96i" = {"16j1" = 0, "16j2" = 1, "16j3" = 2}
"48h" = {"8i1" = 0, "16j1" = 1}
"24g" = {"8h1" = 0, "4f1" = 1}
"24f" = {"8g1" = 0, "4e1" = 2}
"16e" = {"8i1" = 0}
"4d" = {"2d1" = 0}
"4c" = {"2c1" = 0}
"4b" = {"2b1" = 0}
"4a" = {"2a1" = 0}
