space_group_number_sup = 216
space_group_number_sub = 215
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.25, 0.25, 0.25]

[[coset_representatives]]
rotation = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
translation = [0.0, 0.0, 0.0]
[[coset_representatives]]
rotation = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
translation = [0.0, 0.5, 0.5]
[[coset_representatives]]
rotation = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
translation = [0.5, 0.0, 0.5]
[[coset_representatives]]
rotation = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
translation = [0.5, 0.5, 0.0]

[wycksplit]
"96i" = {"24j1" = 0, "24j2" = 1, "24j3" = 2, "24j4" = 3}
"48h" = {"12i1" = 0, "12i2" = 3, "24j2" = 1}
"24g" = {"6f1" = 0, "6g1" = 3, "12h1" = 1}
"24f" = {"12i1" = 0, "12i2" = 3}
"16e" = {"4e1" = 0, "12i1" = 3}
"4d" = {"1b1" = 0, "3d1" = 3}
"4c" = {"1a1" = 0, "3c1" = 3}
"4b" = {"4e1" = 0}
"4a" = {"4e1" = 0}
