space_group_number_sup = 216
space_group_number_sub = 160
basis_change = [[-0.5, 0.0, 1.0], [0.5, -0.5, 1.0], [0.0, 0.5, 1.0]]
origin_shift = [0.0, 0.0, 0.0]

[wycksplit]
[wycksplit.96i]
[wycksplit.96i.18c1]
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]
[wycksplit.96i.18c2]
basis_change = [[-1, 0, 0], [0, -1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]
[wycksplit.96i.18c3]
basis_change = [[1, 0, 0], [0, -1, 0], [0, 0, -1]]
origin_shift = [0.0, 0.0, 0.0]
[wycksplit.96i.18c4]
basis_change = [[-1, 0, 0], [0, 1, 0], [0, 0, -1]]
origin_shift = [0.0, 0.0, 0.0]
[wycksplit.48h]
[wycksplit.48h.9b1]
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]
[wycksplit.48h.9c2]
basis_change = [[-1, 0, 0], [0, -1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]
[wycksplit.48h.18c1]
basis_change = [[1, 0, 0], [0, -1, 0], [0, 0, -1]]
origin_shift = [0.0, 0.0, 0.0]
[wycksplit.24g]
[wycksplit.24g.9b1]
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]
[wycksplit.24g.9b2]
basis_change = [[-1, 0, 0], [0, -1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]
[wycksplit.24h]
[wycksplit.24h.9b1]
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]
[wycksplit.24h.9b2]
basis_change = [[-1, 0, 0], [0, -1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]
[wycksplit.16e]
[wycksplit.16e.3a1]
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]
[wycksplit.16e.9b1]
basis_change = [[-1, 0, 0], [0, -1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]
[wycksplit.4d]
[wycksplit.4d.3a1]
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]
[wycksplit.4c]
[wycksplit.4c.3a1]
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]
[wycksplit.4b]
[wycksplit.4b.3a1]
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]
[wycksplit.4a]
[wycksplit.4a.3a1]
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]
