space_group_number_sup = 216
space_group_number_sub = 160
basis_change = [[-0.5, 0.0, 1.0], [0.5, -0.5, 1.0], [0.0, 0.5, 1.0]]
origin_shift = [0.0, 0.0, 0.0]

[[coset_representatives]]
rotation = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
translation = [0.0, 0.0, 0.0]
[[coset_representatives]]
rotation = [[-1, 0, 0], [0, -1, 0], [0, 0, 1]]
translation = [0.0, 0.0, 0.0]
[[coset_representatives]]
rotation = [[1, 0, 0], [0, -1, 0], [0, 0, -1]]
translation = [0.0, 0.0, 0.0]
[[coset_representatives]]
rotation = [[-1, 0, 0], [0, 1, 0], [0, 0, -1]]
translation = [0.0, 0.0, 0.0]

[wycksplit]
"96i" = {"18c1" = 0, "18c2" = 1, "18c3" = 2, "18c4" = 3}
"48h" = {"9b1" = 0, "9b2" = 1, "18c1" = 2}
"24g" = {"9b1" = 0, "9b2" = 1}
"24h" = {"9b1" = 0, "9b2" = 1}
"16e" = {"3a1" = 0, "9b1" = 1}
"4d" = {"3a1" = 0}
"4c" = {"3a1" = 0}
"4b" = {"3a1" = 0}
"4a" = {"3a1" = 0}
