space_group_number_sup = 216
space_group_number_sub = 196
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]

[[coset_representatives]]
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]
[[coset_representatives]]
basis_change = [[0, 1, 0], [1, 0, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]

[wycksplit]
"96i" = {"48h1" = 0, "48h2" = 1}
"48h" = {"48h1" = 0}
"24g" = {"24g1" = 0}
"24f" = {"24f1" = 0}
"16e" = {"16e1" = 0}
"4d" = {"4d1" = 0}
"4c" = {"4c1" = 0}
"4b" = {"4b1" = 0}
"4a" = {"4a1" = 0}
