space_group_number_sup = 227
space_group_number_sub = 166
basis_change = [[-0.5, 0.0, 1.0], [0.5, -0.5, 1.0], [0.0, 0.5, 1.0]]
origin_shift = [0.0, 0.0, 0.0]

[wycksplit]
[wycksplit.192i]
[wycksplit.192i.36i1]
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]
[wycksplit.192i.36i2]
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, -1]]
origin_shift = [0.25, 0.75, 0.5]
[wycksplit.192i.36i3]
basis_change = [[1, 0, 0], [0, -1, 0], [0, 0, 1]]
origin_shift = [0.75, 0.5, 0.25]
[wycksplit.192i.36i4]
basis_change = [[-1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.5, 0.25, 0.75]
[wycksplit.96h]
[wycksplit.96h.18f1]
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]
[wycksplit.96h.36i1]
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, -1]]
origin_shift = [0.25, 0.75, 0.5]
[wycksplit.96h.18g1]
basis_change = [[-1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.5, 0.25, 0.75]
[wycksplit.96g]
[wycksplit.96g.18h1]
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]
[wycksplit.96g.18h2]
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, -1]]
origin_shift = [0.25, 0.75, 0.5]
[wycksplit.96g.36i1]
basis_change = [[-1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.5, 0.25, 0.75]
[wycksplit.48f]
[wycksplit.48f.18h1]
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]
[wycksplit.48f.18h2]
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, -1]]
origin_shift = [0.25, 0.75, 0.5]
[wycksplit.32e]
[wycksplit.32e.6c1]
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]
[wycksplit.32e.18h1]
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, -1]]
origin_shift = [0.25, 0.75, 0.5]
[wycksplit.16d]
[wycksplit.16d.3b1]
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]
[wycksplit.16d.90]
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, -1]]
origin_shift = [0.25, 0.75, 0.5]
[wycksplit.16c]
[wycksplit.16c.3a1]
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]
[wycksplit.16c.9d1]
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, -1]]
origin_shift = [0.25, 0.75, 0.5]
[wycksplit.8b]
[wycksplit.8b.6c1]
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]
[wycksplit.8a]
[wycksplit.8a.6c1]
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]
