space_group_number_sup = 227
space_group_number_sub = 166
basis_change = [[-0.5, 0.0, 1.0], [0.5, -0.5, 1.0], [0.0, 0.5, 1.0]]
origin_shift = [0.0, 0.0, 0.0]

[[coset_representatives]]
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]
[[coset_representatives]]
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, -1]]
origin_shift = [0.25, 0.75, 0.5]
[[coset_representatives]]
basis_change = [[1, 0, 0], [0, -1, 0], [0, 0, 1]]
origin_shift = [0.75, 0.5, 0.25]
[[coset_representatives]]
basis_change = [[-1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.5, 0.25, 0.75]

[wycksplit]
"192i" = {"36i1" = 0, "36i2" = 1, "36i3" = 2, "36i4" = 3}
"96h" = {"18f1" = 0, "36i1" = 1, "18g1" = 3}
"96g" = {"18h1" = 0, "18h2" = 1, "36i1" = 3}
"48f" = {"18h1" = 0, "18h2" = 1}
"32e" = {"6c1" = 0, "18h1" = 1}
"16d" = {"3b1" = 0, "9e1" = 1}
"16c" = {"3a1" = 0, "9d1" = 1}
"8b" = {"6c1" = 0}
"8a" = {"6c1" = 0}
