space_group_number_sup = 227
space_group_number_sub = 141
basis_change = [[0.5, 0.5, 0.0], [-0.5, 0.5, 0.0], [0.0, 0.0, 1.0]]
origin_shift = [0.25, 0.25, 0.0]

[[coset_representatives]]
rotation = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
translation = [0.0, 0.0, 0.0]
[[coset_representatives]]
rotation = [[0, 0, 1], [1, 0, 0], [0, 1, 0]]
translation = [0.0, 0.0, 0.0]
[[coset_representatives]]
rotation = [[0, 1, 0], [0, 0, 1], [1, 0, 0]]
translation = [0.0, 0.0, 0.0]

[wycksplit]
"192i" = {"32i1" = 0, "32i2" = 1, "32i3" = 2}
"96h" = {"32i1" = 0, "16f1" = 2}
"96g" = {"16h1" = 0, "32i1" = 1}
"48f" = {"16g1" = 0, "8e1" = 2}
"32e" = {"16h1" = 0}
"16d" = {"8d1" = 0}
"16c" = {"8c1" = 0}
"8b" = {"4b1" = 0}
"8a" = {"4a1" = 0}
