space_group_number_sup = 227
space_group_number_sub = 216
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.125, 0.125, 0.125]

[[coset_representatives]]
basis_change = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
origin_shift = [0.0, 0.0, 0.0]
[[coset_representatives]]
basis_change = [[-1, 0, 0], [0, -1, 0], [0, 0, -1]]
origin_shift = [0.0, 0.0, 0.0]

[wycksplit]
"192i" = {"96i1" = 0, "96i2" = 1}
"96h" = {"96i1" = 0}
"96g" = {"48h1" = 0, "48h2" = 1}
"48f" = {"24f1" = 0, "24g1" = 1}
"32e" = {"16e1" = 0, "16e2" = 1}
"16d" = {"16e1" = 0}
"16c" = {"16e1" = 0}
"8b" = {"4c1" = 0, "4b1" = 1}
"8a" = {"4a1" = 0, "4d1" = 1}
